### PR TITLE
Support eapi command revision syntax

### LINKED ISSUE #157: Allow user to specify the version of json command output
Some commands have multiple output versions.  The first (version 1) is the default unless otherwise specified in the request. Example: `show management cvx`.

Valid values: `r'^\d+|latest$'`

kwargs are passed all the way up to the request method which can override the default (1) to a specified value:
https://github.com/arista-eosplus/pyeapi/blob/5470f3b16fac830b101db35ca32068e62abb0162/pyeapi/eapilib.py#L299

### PR DESCRIPTION
**Pull request by jerearista**
Fixes #157

### CODE REVIEW

**Comment by jerearista** [comment]
Release Note:
Support requests for specific revisions of EOS command output
```
>>> node.enable({'cmd': 'show cvx', 'revision': 2})
[{'command': {'cmd': 'show cvx', 'revision': 2},
  'encoding': 'json',
  'result': {u'clusterMode': False,
             u'controllerUUID': u'',
             u'enabled': False,
             u'heartbeatInterval': 20.0,
             u'heartbeatTimeout': 60.0}}]
```

**Comment by mharista** [comment]
Do we expect a revision 2 command to produce the same output for all versions of EOS? If so, can we run the same command for both revisions and verify a unique key for each output in the system test?

**Comment by jerearista** [comment]
Good call.   I added a more detailed set of system tests around command revisions.

**Comment by mharista** [comment]
Looks good to me.

**Pull request merged**
