### PR TITLE
Added support for multiline commands without having to pass them as a dictionary

### PR DESCRIPTION
**Pull request by dbarrosop**
We usually generate full configurations with jinja2 templates and pass them directly to the pyeapi without further processing (we do it via napalm as we have an environment with multiple vendors). The problem comes when we try to execute what you seem to call 'multiline' commands. This PR addresses this problem so you can do something like this:

    >>> import pyeapi
    >>> connection = pyeapi.client.connect(
    ...     transport='https',
    ...     host='192.168.56.201',
    ...     username='vagrant',
    ...     password='vagrant',
    ...     port=443,
    ...     timeout=60
    ... )
    >>> device = pyeapi.client.Node(connection)
    >>> device.run_commands('show hostname')
    [{u'hostname': u'localhost', u'fqdn': u'localhost'}]
    >>> device.run_commands('show banner login')
    [{u'loginBanner': u''}]
    >>> my_commands = [
    ...     'configure session whatever',
    ...     'hostname new-hostname',
    ...     'banner login MULTILINE:This is a new banner\nwith different lines!!!',
    ...     'end'
    ... ]
    >>>
    >>> device.run_commands(my_commands)
    [{}, {}, {}, {}]
    >>> print device.run_commands(['show session-config named whatever diffs'], encoding='text')[0]['output']
    --- system:/running-config
    +++ session:/whatever-session-config
    @@ -3,6 +3,8 @@
     ! boot system flash:/vEOS-lab.swi
     !
     transceiver qsfp default-mode 4x10G
    +!
    +hostname new-hostname
     !
     spanning-tree mode mstp
     !
    @@ -22,6 +24,11 @@
     !
     no ip routing
     !
    +banner login
    +This is a new banner
    +with different lines!!!
    +EOF
    +!
     management api http-commands
        no shutdown
     !
    >>> device.run_commands(['configure session whatever', 'commit'])
    [{}, {}]
    >>> device.run_commands('show hostname')
    [{u'hostname': u'new-hostname', u'fqdn': u'new-hostname'}]
    >>> device.run_commands('show banner login')
    [{u'loginBanner': u'This is a new banner\nwith different lines!!!\n'}]
    >>>

### CODE REVIEW

**Comment by phil-arista** [comment]
Hi Dave - we added native banner support to pyeapi, does that work for you or do you still want to put this in?  The problem with this approach is if you have a series of commands in dicts.  Have a look at https://github.com/arista-eosplus/pyeapi/pull/75 to see if that works for you.

**Comment by dbarrosop** [comment]
Hi! The thing is that we leverage on napalm to write an ansible playbook
that allow us to build and deploy the configuration of all of our vendors
without a single 'if vendor == X then do y'. Your approach would actually
work but would require us to break that rule. The workaround I sent would
allow us to keep doing what we do without any 'ifs'. If you don't want to
merge this PR for some reason we will just add this feature to napalm. So
it's not a big deal, feel free to reject it if you think it goes against
your way of doing things. I just thought it could be interesting for other
people to be able to configure the banner without having to deal with this
one-off.

**Comment by phil-arista** [comment]
Hey, sorry I just saw your reply.  I understand the solution now.  So, we're okay with merging this so long as there are some accompanying unit and system tests.  If you're able to add those then we can kick the tires and then merge.  Thanks!!

**Comment by dbarrosop** [comment]
Thanks! I will try to work on that this weekend : )

**Pull request merged**
