### PR TITLE
Add support for eAPI expandAliases parameter

### LINKED ISSUE #126: `expandAlias` arg for `run_commands`
Hello,

It looks like the Command API provides support to expand aliases:

expandalias

However, this feature does not seem to be supported by the existing `run_commands` method: https://github.com/arista-eosplus/pyeapi/blob/master/pyeapi/client.py#L633

Is there any other possibility to run aliases through eAPI?

Thanks,
Mircea

### PR DESCRIPTION
**Pull request by mharista**
and allow Node methods to send extra eAPI parameters. Fixes #126

### CODE REVIEW

**Comment by devrobo** [comment]
👍

**Comment by mirceaulinic** [comment]
That was really fast, thank you very much! I was actually thinking to come with a similar PR, but you did it already. Great stuff!
I will give it a try and let you know if I notice anything suspicious.
When is this planned to be released?

Thanks,
Mircea

**Comment by mharista** [comment]
@mirceaulinic 

Sure thing. I do not have a set date for the next release yet, but the plan is to pull a set of existing issues into the milestone for the next release and have the time frame set for it this week.

**Comment by mharista** [comment]
Hi @mirceaulinic,

I assessed the existing v0.8.0 milestone and after making a few minor changes am planning to have the release out by the end of February. If possible I will have it out before then and will update you.

**Comment by mirceaulinic** [comment]
Fantastic @mharista! Thank you very much for info!

**Comment by mirceaulinic** [comment]
Just checking in here: do you have any estimated release time? I assume this has been a bit delayed due to new features like https://github.com/arista-eosplus/pyeapi/pull/135 or https://github.com/arista-eosplus/pyeapi/pull/133? Thanks!

**Comment by mharista** [comment]
Hi @mirceaulinic,

Yes the release has been slightly delayed but I am planning to have it out by the end of the week or early next week. I am waiting on a couple more reviews for #135 before merging.

**Comment by mharista** [comment]
Hi @mirceaulinic,

I've just posted the new release that includes this feature here and to pypi.

**Comment by mirceaulinic** [comment]
Awesome! Thank you very much @mharista

**Pull request merged**
