### PR TITLE
fix for route map getall function.

### PR DESCRIPTION
**Pull request by DataSweeper**
Route map getall function not listing the route maps with hyphen character. I have added fix here by changing the regex.

### CODE REVIEW

**Comment by DataSweeper** [comment]
Hi,

  I removed excess code.

  Sample json of routemap api's getall function.

  {'tesing_out_filter': {'permit': {10: {'continue': None, 'match': ['ip address prefix-list Example1'], 'description': None, 'set': []}}}, 'ispfilterout': {'deny': {20: {'continue': None, 'match': ['ip address prefix-list default-deny'], 'description': '"Deny Default"', 'set': []}, 30: {'continue': None, 'match': ['ip address prefix-list private-prefix'], 'description': None, 'set': []}}, 'permit': {10: {'continue': None, 'match': ['ip address prefix-list example-export'], 'description': '"export-self"', 'set': []}}}, 'test-in-list': {'deny': {10: {'continue': None, 'match': ['ip address prefix-list Example'], 'description': 'testing', 'set': []}}}}

  I have added set allow deny method to routemap api. This function helps with BGP advertisement for me. I thought it would be a useful function. So I have pushed that function in this change.

Thanks.

**Comment by mharista** [comment]
Hi @DataSweeper,

Please revert the .gitignore changes as well.
The new method appears to be the same as the existing create method.
Please update the route-map unit and system tests for the getall function with an appropriate example.

**Comment by mharista** [comment]
I've created #154 to add this in without the excess code and the proper tests updated. I'll close this PR when I merge my branch into develop.

**Comment by mharista** [comment]
Merged #154 and closing this.

**Pull request closed without merging**
